[package]
name = "charge_point_simulator_core"
description = "OCPP Charge Point Simulator. Use this library to simulate the use of a charger point"
repository = "https://github.com/flowionab/charge-point-simulator"
license = "MIT OR Apache-2.0"
authors = ["Joatin Granlund <joatin@granlund.io>"]
keywords = ["OCPP", "CP", "ChargePoint", "ocpp16", "ocpp201"]
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
tokio.workspace = true
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
# ocpp-charge-point = { git = "https://github.com/flowionab/ocpp-charge-point", default-features = false }

[dev-dependencies]
tempfile = "3"