use std::collections::VecDeque;

/// Severity of a log entry. `Ord` follows severity: `Error` is the most
/// severe (and smallest) variant, `Trace` the least severe (and largest).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum LogLevel {
    Error,
    Warn,
    Info,
    Debug,
    Trace,
}

/// Which way an OCPP message travelled, when a log entry represents one.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Direction {
    Inbound,
    Outbound,
}

/// A single structured log line.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LogEntry {
    /// "HH:MM:SS.mmm"; `None` for lines generated by the TUI itself rather
    /// than parsed from a tracing event.
    pub timestamp: Option<String>,
    pub level: LogLevel,
    pub target: String,
    pub message: String,
    pub fields: Vec<(String, String)>,
    pub direction: Option<Direction>,
    /// The OCPP action name, e.g. "BootNotification", when known.
    pub action: Option<String>,
}

impl LogEntry {
    /// Elide the module path down to a short `crate::last_segment` form.
    ///
    /// A leading `charge_point_simulator_` prefix on the first segment is
    /// stripped. If more than two segments remain after that, only the
    /// first and last are kept, joined by `::`. Targets without `::` are
    /// returned as-is (minus the prefix).
    pub fn short_target(&self) -> String {
        let segments: Vec<&str> = self.target.split("::").collect();
        if segments.is_empty() {
            return self.target.clone();
        }

        let first = segments[0]
            .strip_prefix("charge_point_simulator_")
            .unwrap_or(segments[0]);

        if segments.len() == 1 {
            return first.to_string();
        }

        if segments.len() > 2 {
            let last = segments[segments.len() - 1];
            format!("{first}::{last}")
        } else {
            format!("{first}::{}", segments[1])
        }
    }

    /// Case-insensitive substring match against message, target, and action.
    pub fn matches(&self, needle: &str) -> bool {
        let needle = needle.to_lowercase();
        self.message.to_lowercase().contains(&needle)
            || self.target.to_lowercase().contains(&needle)
            || self
                .action
                .as_ref()
                .is_some_and(|action| action.to_lowercase().contains(&needle))
    }
}

impl From<&str> for LogEntry {
    fn from(message: &str) -> Self {
        LogEntry {
            timestamp: None,
            level: LogLevel::Info,
            target: "tui".to_string(),
            message: message.to_string(),
            fields: Vec::new(),
            direction: None,
            action: None,
        }
    }
}

impl From<String> for LogEntry {
    fn from(message: String) -> Self {
        LogEntry {
            timestamp: None,
            level: LogLevel::Info,
            target: "tui".to_string(),
            message,
            fields: Vec::new(),
            direction: None,
            action: None,
        }
    }
}

/// A scrolling log of session events, newest entry last.
///
/// The buffer auto-follows the tail of the log by default. Scrolling up
/// pauses that follow behavior so the view holds still even as new entries
/// arrive underneath; scrolling back down to the bottom resumes it.
///
/// Backed by a bounded ring of at most [`LogBuffer::CAPACITY`] entries;
/// pushing beyond capacity drops the oldest entry. The filtered/thresholded
/// view is cached as a list of indices into the ring, rebuilt only when the
/// buffer, filter, or level threshold changes.
#[derive(Debug, Clone)]
pub struct LogBuffer {
    entries: VecDeque<LogEntry>,
    scroll_offset: usize,
    filter: Option<String>,
    level_threshold: LogLevel,
    filtered_cache: Vec<usize>,
}

impl LogBuffer {
    /// Maximum number of entries retained; pushing beyond this drops the
    /// oldest entry.
    pub const CAPACITY: usize = 5000;

    pub fn push(&mut self, entry: impl Into<LogEntry>) {
        let entry = entry.into();
        let matches = self.passes_filters(&entry);

        let evicted = if self.entries.len() >= Self::CAPACITY {
            self.entries.pop_front();
            true
        } else {
            false
        };
        self.entries.push_back(entry);

        if evicted {
            // Every cached index shifts down by one; drop any that pointed
            // at the evicted (now-gone) entry.
            self.filtered_cache.retain_mut(|index| {
                if *index == 0 {
                    false
                } else {
                    *index -= 1;
                    true
                }
            });
            // `scroll_offset` is a distance from the *tail*, so losing an entry off the front
            // doesn't move the view - only pushing onto the tail does (handled below). The one
            // case eviction does affect is a view scrolled so far back that its anchor is the
            // entry that just fell out; the clamp at the end of this function catches that.
        }

        if matches {
            self.filtered_cache.push(self.entries.len() - 1);
            if self.is_paused() {
                self.scroll_offset += 1;
            }
        }

        // Can only bite after an eviction: the offset now points past the oldest surviving
        // entry, so pin it to that entry rather than letting `visible_lines` show nothing.
        let max_offset = self.filtered_cache.len().saturating_sub(1);
        self.scroll_offset = self.scroll_offset.min(max_offset);
    }

    /// Whether the view is scrolled up and no longer following the live tail.
    pub fn is_paused(&self) -> bool {
        self.scroll_offset > 0
    }

    pub fn scroll_up(&mut self) {
        let max_offset = self.filtered_len().saturating_sub(1);
        if self.scroll_offset < max_offset {
            self.scroll_offset += 1;
        }
    }

    pub fn scroll_down(&mut self) {
        self.scroll_offset = self.scroll_offset.saturating_sub(1);
    }

    /// Anchor the view on the oldest visible entry.
    pub fn scroll_to_top(&mut self) {
        self.scroll_offset = self.filtered_len().saturating_sub(1);
    }

    /// Resume following the live tail.
    pub fn scroll_to_bottom(&mut self) {
        self.scroll_offset = 0;
    }

    pub fn set_filter(&mut self, filter: impl Into<String>) {
        self.filter = Some(filter.into());
        self.scroll_offset = 0;
        self.rebuild_cache();
    }

    pub fn clear_filter(&mut self) {
        self.filter = None;
        self.scroll_offset = 0;
        self.rebuild_cache();
    }

    pub fn filter(&self) -> Option<&str> {
        self.filter.as_deref()
    }

    pub fn level_threshold(&self) -> LogLevel {
        self.level_threshold
    }

    /// Cycle Info -> Debug -> Trace -> Error -> Warn -> Info.
    pub fn cycle_level_threshold(&mut self) {
        self.level_threshold = match self.level_threshold {
            LogLevel::Info => LogLevel::Debug,
            LogLevel::Debug => LogLevel::Trace,
            LogLevel::Trace => LogLevel::Error,
            LogLevel::Error => LogLevel::Warn,
            LogLevel::Warn => LogLevel::Info,
        };
        self.scroll_offset = 0;
        self.rebuild_cache();
    }

    /// Number of entries currently passing the filter and level threshold.
    pub fn filtered_len(&self) -> usize {
        self.filtered_cache.len()
    }

    pub fn scroll_offset(&self) -> usize {
        self.scroll_offset
    }

    /// The `height` most recent entries that should be visible, oldest
    /// first, honoring the current filter, level threshold, and scroll
    /// position. `scroll_offset` picks which entry anchors the bottom of the
    /// view; near the oldest entry this can yield fewer than `height`
    /// entries rather than padding with newer ones the scroll position has
    /// intentionally moved past.
    pub fn visible_lines(&self, height: usize) -> Vec<&LogEntry> {
        let filtered = self.filtered();
        if filtered.is_empty() || height == 0 {
            return Vec::new();
        }

        let last_index = filtered.len() - 1;
        let bottom_index = last_index.saturating_sub(self.scroll_offset);
        let start_index = bottom_index.saturating_sub(height - 1);
        filtered[start_index..=bottom_index].to_vec()
    }

    fn passes_filters(&self, entry: &LogEntry) -> bool {
        if entry.level > self.level_threshold {
            return false;
        }
        match &self.filter {
            Some(filter) => entry.matches(filter),
            None => true,
        }
    }

    fn rebuild_cache(&mut self) {
        self.filtered_cache = self
            .entries
            .iter()
            .enumerate()
            .filter(|(_, entry)| self.passes_filters(entry))
            .map(|(index, _)| index)
            .collect();
    }

    fn filtered(&self) -> Vec<&LogEntry> {
        self.filtered_cache
            .iter()
            .map(|&index| &self.entries[index])
            .collect()
    }
}

impl Default for LogBuffer {
    fn default() -> Self {
        LogBuffer {
            entries: VecDeque::new(),
            scroll_offset: 0,
            filter: None,
            level_threshold: LogLevel::Info,
            filtered_cache: Vec::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn messages(entries: Vec<&LogEntry>) -> Vec<String> {
        entries.into_iter().map(|e| e.message.clone()).collect()
    }

    #[test]
    fn a_new_buffer_is_empty_and_not_paused() {
        let logs = LogBuffer::default();
        assert!(logs.visible_lines(5).is_empty());
        assert!(!logs.is_paused());
    }

    #[test]
    fn visible_lines_shows_the_most_recent_entries_first_to_last() {
        let mut logs = LogBuffer::default();
        for line in ["one", "two", "three", "four"] {
            logs.push(line);
        }

        assert_eq!(messages(logs.visible_lines(2)), vec!["three", "four"]);
    }

    #[test]
    fn visible_lines_returns_everything_when_the_buffer_is_shorter_than_the_height() {
        let mut logs = LogBuffer::default();
        logs.push("only one");

        assert_eq!(messages(logs.visible_lines(5)), vec!["only one"]);
    }

    #[test]
    fn scrolling_up_pauses_and_holds_the_view_steady_as_new_entries_arrive() {
        let mut logs = LogBuffer::default();
        for line in ["one", "two", "three", "four"] {
            logs.push(line);
        }

        logs.scroll_up();
        assert!(logs.is_paused());
        let before = messages(logs.visible_lines(2));
        assert_eq!(before, vec!["two", "three"]);

        logs.push("five");
        let after = messages(logs.visible_lines(2));
        assert_eq!(before, after);
    }

    #[test]
    fn scroll_up_stops_once_the_oldest_entry_reaches_the_bottom_of_the_view() {
        let mut logs = LogBuffer::default();
        for line in ["one", "two"] {
            logs.push(line);
        }

        for _ in 0..10 {
            logs.scroll_up();
        }

        assert_eq!(messages(logs.visible_lines(5)), vec!["one"]);
    }

    #[test]
    fn scrolling_back_down_to_the_bottom_resumes_following_the_tail() {
        let mut logs = LogBuffer::default();
        for line in ["one", "two", "three"] {
            logs.push(line);
        }

        logs.scroll_up();
        logs.scroll_up();
        assert!(logs.is_paused());

        logs.scroll_down();
        logs.scroll_down();
        assert!(!logs.is_paused());
        assert_eq!(messages(logs.visible_lines(2)), vec!["two", "three"]);
    }

    #[test]
    fn scroll_down_at_the_bottom_does_not_panic() {
        let mut logs = LogBuffer::default();
        logs.push("one");
        logs.scroll_down();
        assert!(!logs.is_paused());
    }

    #[test]
    fn filter_hides_non_matching_entries() {
        let mut logs = LogBuffer::default();
        logs.push("connector 1 available");
        logs.push("connector 2 faulted");
        logs.push("heartbeat sent");

        logs.set_filter("fault");
        assert_eq!(
            messages(logs.visible_lines(10)),
            vec!["connector 2 faulted"]
        );
    }

    #[test]
    fn filter_matching_is_case_insensitive() {
        let mut logs = LogBuffer::default();
        logs.push("Connector Faulted");

        logs.set_filter("FAULT");
        assert_eq!(messages(logs.visible_lines(10)), vec!["Connector Faulted"]);
    }

    #[test]
    fn clearing_the_filter_restores_every_entry() {
        let mut logs = LogBuffer::default();
        logs.push("one");
        logs.push("two");

        logs.set_filter("one");
        logs.clear_filter();

        assert_eq!(messages(logs.visible_lines(10)), vec!["one", "two"]);
    }

    #[test]
    fn filter_accessor_reports_the_active_filter() {
        let mut logs = LogBuffer::default();
        assert_eq!(logs.filter(), None);

        logs.set_filter("fault");
        assert_eq!(logs.filter(), Some("fault"));

        logs.clear_filter();
        assert_eq!(logs.filter(), None);
    }

    #[test]
    fn pushing_a_non_matching_entry_while_paused_does_not_shift_the_view() {
        let mut logs = LogBuffer::default();
        logs.push("connector faulted");
        logs.push("heartbeat sent");
        logs.set_filter("fault");

        logs.push("connector faulted again");
        assert!(!logs.is_paused());

        logs.scroll_up();
        let before = messages(logs.visible_lines(1));
        logs.push("heartbeat sent again");
        let after = messages(logs.visible_lines(1));
        assert_eq!(before, after);
    }

    #[test]
    fn log_level_ord_ranks_error_as_most_severe() {
        assert!(LogLevel::Error < LogLevel::Warn);
        assert!(LogLevel::Warn < LogLevel::Info);
        assert!(LogLevel::Info < LogLevel::Debug);
        assert!(LogLevel::Debug < LogLevel::Trace);
    }

    #[test]
    fn from_str_produces_an_info_level_tui_entry() {
        let entry: LogEntry = "hello".into();
        assert_eq!(entry.level, LogLevel::Info);
        assert_eq!(entry.target, "tui");
        assert_eq!(entry.timestamp, None);
        assert_eq!(entry.message, "hello");
        assert!(entry.fields.is_empty());
        assert_eq!(entry.direction, None);
        assert_eq!(entry.action, None);
    }

    #[test]
    fn from_string_produces_an_info_level_tui_entry() {
        let entry: LogEntry = String::from("hello").into();
        assert_eq!(entry.level, LogLevel::Info);
        assert_eq!(entry.target, "tui");
        assert_eq!(entry.message, "hello");
    }

    #[test]
    fn short_target_strips_the_crate_prefix_and_middle_segments() {
        let mut entry: LogEntry = "msg".into();
        entry.target = "charge_point_simulator_core::charger::state".to_string();
        assert_eq!(entry.short_target(), "core::state");

        entry.target = "charge_point_simulator_tui::app".to_string();
        assert_eq!(entry.short_target(), "tui::app");
    }

    #[test]
    fn short_target_returns_a_single_segment_as_is_minus_prefix() {
        let mut entry: LogEntry = "msg".into();
        entry.target = "charge_point_simulator_core".to_string();
        assert_eq!(entry.short_target(), "core");

        entry.target = "tokio".to_string();
        assert_eq!(entry.short_target(), "tokio");
    }

    #[test]
    fn short_target_keeps_two_segments_unchanged_besides_the_prefix() {
        let mut entry: LogEntry = "msg".into();
        entry.target = "charge_point_simulator_core::charger".to_string();
        assert_eq!(entry.short_target(), "core::charger");
    }

    #[test]
    fn matches_checks_message_target_and_action_case_insensitively() {
        let entry = LogEntry {
            timestamp: None,
            level: LogLevel::Info,
            target: "core::ocpp".to_string(),
            message: "sent heartbeat".to_string(),
            fields: Vec::new(),
            direction: Some(Direction::Outbound),
            action: Some("BootNotification".to_string()),
        };

        assert!(entry.matches("HEARTBEAT"));
        assert!(entry.matches("ocpp"));
        assert!(entry.matches("bootnotification"));
        assert!(!entry.matches("nonexistent"));
    }

    #[test]
    fn level_threshold_defaults_to_info_and_hides_less_severe_entries() {
        let mut logs = LogBuffer::default();
        assert_eq!(logs.level_threshold(), LogLevel::Info);

        logs.push(LogEntry {
            timestamp: None,
            level: LogLevel::Debug,
            target: "core".to_string(),
            message: "debug entry".to_string(),
            fields: Vec::new(),
            direction: None,
            action: None,
        });
        logs.push("info entry");

        assert_eq!(messages(logs.visible_lines(10)), vec!["info entry"]);
    }

    #[test]
    fn cycle_level_threshold_follows_the_documented_order() {
        let mut logs = LogBuffer::default();
        assert_eq!(logs.level_threshold(), LogLevel::Info);

        logs.cycle_level_threshold();
        assert_eq!(logs.level_threshold(), LogLevel::Debug);

        logs.cycle_level_threshold();
        assert_eq!(logs.level_threshold(), LogLevel::Trace);

        logs.cycle_level_threshold();
        assert_eq!(logs.level_threshold(), LogLevel::Error);

        logs.cycle_level_threshold();
        assert_eq!(logs.level_threshold(), LogLevel::Warn);

        logs.cycle_level_threshold();
        assert_eq!(logs.level_threshold(), LogLevel::Info);
    }

    #[test]
    fn changing_level_threshold_resets_scroll_to_the_bottom() {
        let mut logs = LogBuffer::default();
        for line in ["one", "two", "three"] {
            logs.push(line);
        }
        logs.scroll_up();
        assert!(logs.is_paused());

        logs.cycle_level_threshold();
        assert!(!logs.is_paused());
        assert_eq!(logs.scroll_offset(), 0);
    }

    #[test]
    fn scroll_to_top_anchors_on_the_oldest_visible_entry() {
        let mut logs = LogBuffer::default();
        for line in ["one", "two", "three"] {
            logs.push(line);
        }

        logs.scroll_to_top();
        assert_eq!(messages(logs.visible_lines(1)), vec!["one"]);
    }

    #[test]
    fn scroll_to_bottom_resumes_following_the_tail() {
        let mut logs = LogBuffer::default();
        for line in ["one", "two", "three"] {
            logs.push(line);
        }

        logs.scroll_to_top();
        assert!(logs.is_paused());

        logs.scroll_to_bottom();
        assert!(!logs.is_paused());
        assert_eq!(messages(logs.visible_lines(1)), vec!["three"]);
    }

    #[test]
    fn filtered_len_and_scroll_offset_report_scrollbar_state() {
        let mut logs = LogBuffer::default();
        for line in ["one", "two", "three"] {
            logs.push(line);
        }
        assert_eq!(logs.filtered_len(), 3);
        assert_eq!(logs.scroll_offset(), 0);

        logs.scroll_up();
        assert_eq!(logs.scroll_offset(), 1);

        logs.set_filter("two");
        assert_eq!(logs.filtered_len(), 1);
    }

    #[test]
    fn pushing_beyond_capacity_drops_the_oldest_entry() {
        let mut logs = LogBuffer::default();
        for i in 0..(LogBuffer::CAPACITY + 10) {
            logs.push(format!("entry {i}"));
        }

        assert_eq!(logs.filtered_len(), LogBuffer::CAPACITY);
        assert_eq!(
            messages(logs.visible_lines(1)),
            vec![format!("entry {}", LogBuffer::CAPACITY + 9)]
        );
        assert_eq!(
            messages(logs.visible_lines(LogBuffer::CAPACITY))[0],
            "entry 10"
        );
    }

    #[test]
    fn eviction_while_paused_adjusts_scroll_offset_so_the_view_does_not_shift() {
        let mut logs = LogBuffer::default();
        for i in 0..LogBuffer::CAPACITY {
            logs.push(format!("entry {i}"));
        }

        // Pause a few entries up from the tail.
        logs.scroll_up();
        logs.scroll_up();
        let before = messages(logs.visible_lines(1));

        // Push past capacity: this evicts an old entry the paused view was
        // never anchored on, so the visible entry should not change.
        logs.push("overflow");

        let after = messages(logs.visible_lines(1));
        assert_eq!(before, after);
    }

    #[test]
    fn filtered_view_stays_correct_after_repeated_pushes_eviction_and_filter_changes() {
        let mut logs = LogBuffer::default();
        for i in 0..(LogBuffer::CAPACITY + 50) {
            let msg = if i % 2 == 0 {
                format!("even {i}")
            } else {
                format!("odd {i}")
            };
            logs.push(msg);

            // Read repeatedly to exercise the cache without mutating it.
            let _ = logs.visible_lines(3);
            let _ = logs.visible_lines(3);
        }

        // Every entry present in the ring should be "odd" only, once filtered.
        logs.set_filter("odd");
        let expected_count = logs
            .visible_lines(LogBuffer::CAPACITY)
            .iter()
            .filter(|e| e.message.starts_with("odd"))
            .count();
        assert_eq!(expected_count, logs.filtered_len());
        assert!(
            logs.visible_lines(LogBuffer::CAPACITY)
                .iter()
                .all(|e| e.message.starts_with("odd"))
        );

        logs.clear_filter();
        assert_eq!(logs.filtered_len(), LogBuffer::CAPACITY);
    }
}
